#!/usr/bin/env bash

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export HARNESS_ROOT="${HARNESS_ROOT:-${ROOT_DIR}/target/harness}"
export HARNESS_STATE_DIR="${HARNESS_STATE_DIR:-${HARNESS_ROOT}/wrangler-state}"
export HARNESS_LOG_DIR="${HARNESS_LOG_DIR:-${HARNESS_ROOT}/logs}"
export HARNESS_ASSERT_DIR="${HARNESS_ASSERT_DIR:-${HARNESS_ROOT}/assertions}"

export HARNESS_HOST="${HARNESS_HOST:-127.0.0.1}"
export HARNESS_API_PORT="${HARNESS_API_PORT:-8787}"
export HARNESS_PIPELINE_PORT="${HARNESS_PIPELINE_PORT:-8788}"
export HARNESS_WEB_PORT="${HARNESS_WEB_PORT:-5173}"
export HARNESS_API_INSPECTOR_PORT="${HARNESS_API_INSPECTOR_PORT:-9229}"
export HARNESS_PIPELINE_INSPECTOR_PORT="${HARNESS_PIPELINE_INSPECTOR_PORT:-9230}"

export HARNESS_API_URL="http://${HARNESS_HOST}:${HARNESS_API_PORT}"
export HARNESS_PIPELINE_URL="http://${HARNESS_HOST}:${HARNESS_PIPELINE_PORT}"
export HARNESS_WEB_URL="http://${HARNESS_HOST}:${HARNESS_WEB_PORT}"

export HARNESS_FIXTURE_SET="${HARNESS_FIXTURE_SET:-canonical}"
export HARNESS_NOW="${HARNESS_NOW:-2026-01-20T15:00:00Z}"
export HARNESS_EXPECTED_VOTE_ID="${HARNESS_EXPECTED_VOTE_ID:-119:2:14}"
export HARNESS_EXPECTED_VOTE_TITLE="${HARNESS_EXPECTED_VOTE_TITLE:-Border Infrastructure Modernization Act}"
export HARNESS_EXPECTED_VOTE_NUMBER="${HARNESS_EXPECTED_VOTE_NUMBER:-14}"
export HARNESS_INGEST_MAX_TIME="${HARNESS_INGEST_MAX_TIME:-180}"
