#!/usr/bin/env bash

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export HARNESS_ROOT="${HARNESS_ROOT:-${ROOT_DIR}/target/harness}"
export HARNESS_STATE_DIR="${HARNESS_STATE_DIR:-${HARNESS_ROOT}/wrangler-state}"
export HARNESS_LOG_DIR="${HARNESS_LOG_DIR:-${HARNESS_ROOT}/logs}"
export HARNESS_ASSERT_DIR="${HARNESS_ASSERT_DIR:-${HARNESS_ROOT}/assertions}"

export HARNESS_HOST="${HARNESS_HOST:-127.0.0.1}"
export HARNESS_API_PORT="${HARNESS_API_PORT:-8787}"
export HARNESS_WEB_PORT="${HARNESS_WEB_PORT:-5173}"
export HARNESS_API_INSPECTOR_PORT="${HARNESS_API_INSPECTOR_PORT:-9229}"

export HARNESS_API_URL="http://${HARNESS_HOST}:${HARNESS_API_PORT}"
# The unified worker serves both the public API and the /__pipeline/* admin routes,
# so the pipeline URL is the same origin as the API.
export HARNESS_PIPELINE_URL="${HARNESS_API_URL}"
export HARNESS_WEB_URL="http://${HARNESS_HOST}:${HARNESS_WEB_PORT}"

export REPLAY_FIXTURE_SET="${REPLAY_FIXTURE_SET:-canonical}"
export CLOCK="${CLOCK:-2026-01-20T15:00:00Z}"
export HARNESS_EXPECTED_VOTE_ID="${HARNESS_EXPECTED_VOTE_ID:-119:2:14}"
export HARNESS_EXPECTED_VOTE_TITLE="${HARNESS_EXPECTED_VOTE_TITLE:-Border Infrastructure Modernization Act}"
export HARNESS_INGEST_MAX_TIME="${HARNESS_INGEST_MAX_TIME:-180}"

IFS=':' read -r HARNESS_VOTE_CONGRESS HARNESS_VOTE_SESSION HARNESS_VOTE_NUMBER <<<"${HARNESS_EXPECTED_VOTE_ID}"
export HARNESS_VOTE_CONGRESS HARNESS_VOTE_SESSION HARNESS_VOTE_NUMBER
export HARNESS_EXPECTED_VOTE_DETAIL_PATH="/votes/${HARNESS_VOTE_CONGRESS}/${HARNESS_VOTE_SESSION}/${HARNESS_VOTE_NUMBER}"
export HARNESS_EXPECTED_VOTE_DETAIL_API_PATH="${HARNESS_EXPECTED_VOTE_DETAIL_PATH}.json"
# Back-compat alias for scripts/tests that still read HARNESS_EXPECTED_VOTE_NUMBER.
export HARNESS_EXPECTED_VOTE_NUMBER="${HARNESS_VOTE_NUMBER}"

export HARNESS_PREVIEW_ROOT="${HARNESS_PREVIEW_ROOT:-${ROOT_DIR}/target/preview}"
